---
resources:
  - name: config-server-repo
    type: git
    source:
      uri: https://github.com/categolj/config-server
      branch: master
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: {{docker-repo}}

jobs:
  - name: config-server-unit
    plan:
      - get: config-server-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: config-server-repo
              path: repo
            - name: m2  
          run:
            path: sh
            args: 
            - repo/ci/tasks/unit.sh
  - name: config-server-deploy
    plan:
      - get: config-server-repo
        trigger: true
        passed: [ config-server-unit ]
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: config-server-repo
              path: repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: config-server-repo/manifest.yml
          path: output/app.jar
          current_app_name: blog-config


  - name: config-server-create-service
    plan:
      - task: create-service
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
          run:
            path: sh
            args:
            - -c
            - |
              cred='{"uri":"http://'{{config-username}}'@'{{config-password}}':blog-config.cfapps.pez.pivotal.io"}'
              cf login -a {{cf-api}} -u {{cf-username}} -p {{cf-password}} -o {{cf-org}} -s {{cf-space}}
              cf create-user-provided-service config-service -p $cred